# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'AceleraChat'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/acelerachat/symbol.svg'
- name: LOGO
  value: '/brand-assets/acelerachat/logo.svg'
- name: LOGO_DARK
  value: '/brand-assets/acelerachat/logo-dark.svg'
- name: BRAND_URL
  value: 'https://atendimento.meugerenciador.pro'
- name: WIDGET_BRAND_URL
  value: 'https://atendimento.meugerenciador.pro'
- name: BRAND_NAME
  value: 'AceleraChat'
- name: TERMS_URL
  value: '/legal/terms'
- name: PRIVACY_URL
  value: '/legal/privacy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
